[package]
name = "mentat"
version = "0.4.0"
authors = ["Richard Newman <rnewman@twinql.com>", "Nicholas Alexander <nalexander@mozilla.com>"]

[dependencies]
rusqlite = "0.8.0"

[dependencies.mentat_query_parser]
  path = "query-parser"

[dev-dependencies]
[dev-dependencies.mentat_cli]
  path = "cli"

[[bin]]
name = "mentat_cli"
path = "cli/src/main.rs"
